### ISSUE TITLE
entrada.id must be autoincremental field

### ISSUE THREAD

**Issue by Japoivvb** [Adriaris/dam2tm06uf2p2#1]
1. entrada.id generated by Hibernate using model.Entrada should be autoincremental to allow insert data in field instruction with an error regarding duplicated query.

2. set issue label as bug to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 
e.g. #1 adds incremental id logic

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Adriaris** [comment]
![entrada-id-autoincremental](https://github.com/Adriaris/dam2tm06uf2p2/assets/124537287/4e9cffe5-0035-4cd8-82bf-a2fca8e8966f)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok, better database evidence
5. ko, I must close the issue
