### ISSUE TITLE
action # vendimia is only processing last campo of last bodega, not previous records

### ISSUE THREAD

**Issue by Japoivvb** [Adriaris/dam2tm06uf2p2#3]
1. when vendimia is processed previous records are not being processed, e.g. vid 3,4,17,18

2. set issue label as bug to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Adriaris** [comment]
![issue 3](https://github.com/Adriaris/dam2tm06uf2p2/assets/124537287/45083aa7-2663-44aa-b115-5c1b1babf0c0)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ko, I must close the issue
