### ISSUE TITLE
add new field precio to vid model 

### ISSUE THREAD

**Issue by Japoivvb** [Adriaris/dam2tm06uf2p2#4]
1. add double precio attribute to vid model and verify everything is working again

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Adriaris** [comment]
![issue 3](https://github.com/Adriaris/dam2tm06uf2p2/assets/124537287/090d2103-9949-46bb-9473-08a7e7c6349b)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ko, it does not show price evidence
5. ok
