### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [Adriaris/dam2tm06uf2p2#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Adriaris** [comment]
![image](https://github.com/Adriaris/dam2tm06uf2p2/assets/124537287/fe254426-465a-409c-800e-651e93840f7f)

**Comment by Adriaris** [comment]
Read the 'Entrada' collection from MongoDB and write to MySQL.

Antes de migrar todo primero migré solo la lectura de la tabla Entrada desde MongoDB pero seguía escribiendo en MySQL. Hice un commit a la rama pero sin el #6. 
![Captura de pantalla 2024-05-02 215048](https://github.com/Adriaris/dam2tm06uf2p2/assets/124537287/b47b95c9-d5ec-4d8a-96eb-59db30349825)

**Comment by Adriaris** [comment]
![image](https://github.com/Adriaris/dam2tm06uf2p2/assets/124537287/8a3c40e8-619c-45a2-9619-a8d77a79a4f0)

**Comment by Japoivvb** [comment]
1. ok
2. ko, it was enhancement
3. ok
4. ok
5. ok
excellent job, one of the best performance of the class
